package com.iks.dddschach.domain.validation;

/**
 * Created by vollmer on 02.06.17.
 */
public enum Zugregel {
    SPIELFIGUR_MUSS_EXISTIEREN,
    SPIELER_MUSS_AM_ZUG_SEIN,
    ZUG_STRECKE_MUSS_FREI_SEIN,
    LAUEFER_ZIEHT_DIAGONAL,
    TURM_ZIEHT_GERADE,
    DAME_ZIEHT_GERADE_ODER_DIAGONAL,
    KOENIG_ZIEHT_NUR_EIN_FELD,
    PFERD_ZIEHT_EINEN_WINKEL,
    KOENIG_KANN_NICHT_GESCHLAGEN_WERDEN,
    BAUER_SCHLAEGT_NUR_SCHRAEG,
    BAUER_ZIEHT_NUR_EIN_FELD_AUSSER_AM_ANFANG,
    KOENIG_STEHT_IM_SCHACH
}
